apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sfe4j
spec:
  selector:
    matchLabels:
      app: sfe4j
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: sfe4j
    spec:
      containers:
      - name: sfe4j
        image: docker.amoylabs.com:30500/sfe4j:5
        ports:
        - name: http
          containerPort: 8080
