version: '3.8'

services:
  app:
    container_name: nuxt-starter
    image: cr.amoylabs.com/guuuuo/nuxt-starter:32
    restart: always
    
networks:
  default:
    external: true
    name: proxy-net